export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SET_MODAL = "SET_MODAL";

export const UNSHIFT_HISTORY = "UNSHIFT_HISTORY";

export const ADDING_TO_CART = "ADDING_TO_CART";
export const ADDED_TO_CART = "ADDED_TO_CART";
export const ADDING_TO_CART_ERROR = "ADDING_TO_CART_ERROR";
