export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SET_MODAL = "SET_MODAL";
export const GET_CART_AMOUNT = "GET_CART_AMOUNT";

export const ADDING_TO_CART = "ADDING_TO_CART";
export const ADDED_TO_CART = "ADDED_TO_CART";
export const ADDING_TO_CART_ERROR = "ADDING_TO_CART_ERROR";

export const REMOVING_ITEM_FROM_CART = "REMOVING_ITEM_FROM_CART";
export const REMOVED_ITEM_FROM_CART = "REMOVED_ITEM_FROM_CART";
export const REMOVING_ITEM_FROM_CART_ERROR = "REMOVING_ITEM_FROM_CART_ERROR";

export const FETCHING_CART_ITEMS = "FETCHING_CART_ITEMS";
export const FETCHED_CART_ITEMS = "FETCHED_CART_ITEMS";
export const FETCHING_CART_ITEMS_ERROR = "FETCHING_CART_ITEMS_ERROR";

export const CLEARING_CART_ITEMS = "CLEARING_CART_ITEMS";
export const CLEARED_CART_ITEMS = "CLEARED_CART_ITEMS";
export const CLEARING_CART_ITEMS_ERROR = "CLEARING_CART_ITEMS_ERROR";


export const FETCHING_FAVORITE_ITEMS = "FETCHING_FAVORITE_ITEMS";
export const FETCHED_FAVORITE_ITEMS = "FETCHED_FAVORITE_ITEMS";
export const FETCHING_FAVORITE_ITEMS_ERROR = "FETCHING_FAVORITE_ITEMS_ERROR";

export const ADDING_ITEM_TO_FAVORITES = "ADDING_ITEM_TO_FAVORITES";
export const ADDED_ITEM_TO_FAVORITES = "ADDED_ITEM_TO_FAVORITES";
export const ADDING_ITEM_TO_FAVORITES_ERROR = "ADDING_ITEM_TO_FAVORITES_ERROR";

export const REMOVING_ITEM_FROM_FAVORITES = "REMOVING_ITEM_FROM_FAVORITES";
export const REMOVED_ITEM_FROM_FAVORITES = "REMOVED_ITEM_FROM_FAVORITES";
export const REMOVING_ITEM_FROM_FAVORITES_ERROR = "REMOVING_ITEM_FROM_FAVORITES_ERROR";
