import "./Button/Button.stories";
import "./Input/Input.stories";
import "./Text/Text.stories";
import "./FavoriteCard.stories";
import "./OrderCard.stories";
import "./SearchCard/SearchCard.stories";
import "./OrderProductCard.stories";
import "./CartProductCard.stories";
import "./CardContainer/CardContainer.stories";
import "./CategoryContainer/CategoryContainer.stories";
import "./ScrollContainer/ScrollContainer.stories";
import "./Card/Card.stories";

// Organisms
import "./FavoriteCard.stories";
import "./Home.stories";
import "./Header.stories";
// Views
import "./CategorySearch/CategorySearch.stories";
import "./Pages/Cart.stories";
import "./Pages/Orders.stories";
import "./Pages/Payment.stories";
